### ISSUE TITLE
Required argument access_key is missing

### ISSUE THREAD

**Issue by paulius005** [zuazo/chef_handler_sns-cookbook#5]
`chef_handler_sns-cookbook` version `3.0.0`

I have taken the `aws-opsworks-service-role` and `aws-opsworks-ec2-role` roles and added the following policies to them

for `aws-opsworks-service-role`:
<img width="936" alt="screen shot 2017-05-12 at 8 09 24 pm" src="https://cloud.githubusercontent.com/assets/3084367/26022056/0a7171e4-374f-11e7-99ac-f48c12ae80d7.png">

At the stack level:
the IAM role is :`aws-opsworks-service-role`
and the Default IAM instance profile is: `aws-opsworks-ec2-role`

for `aws-opsworks-ec2-role`:
<img width="854" alt="screen shot 2017-05-12 at 8 10 35 pm" src="https://cloud.githubusercontent.com/assets/3084367/26022057/1b460b74-374f-11e7-8034-f2236bae2bf0.png">

with `SNSPublish` containing the following
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1494612602000",
            "Effect": "Allow",
            "Action": [
                "sns:Publish"
            ],
            "Resource": [
                "arn:aws:sns:us-west-1:123412341234:opsworks-handler-notifications"
            ]
        }
    ]
}
```

I am running this recipe in my own recipe in the following way:

`chef_handler_sns 'arn:aws:sns:us-west-1:123412341234:opsworks-handler-notifications`

All the default values are left as provided in `chef_handler_sns/attributes/default.rb`

But I keep getting the following: `Required argument access_key is missing!`
```
[2017-05-13T01:54:24+00:00] ERROR: Report handler Chef::Handler::Sns raised #<Chef::Exceptions::ValidationFailed: Required argument access_key is missing!>
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-handler-sns-2.1.0/lib/chef/handler/sns/config.rb:109:in `block in config_check'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-handler-sns-2.1.0/lib/chef/handler/sns/config.rb:107:in `each'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-handler-sns-2.1.0/lib/chef/handler/sns/config.rb:107:in `config_check'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-handler-sns-2.1.0/lib/chef/handler/sns.rb:134:in `report'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/handler.rb:259:in `run_report_unsafe'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/handler.rb:247:in `run_report_safely'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/handler.rb:125:in `block in run_report_handlers'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/handler.rb:123:in `each'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/handler.rb:123:in `run_report_handlers'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/handler.rb:135:in `block in <class:Handler>'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:441:in `block in run_completed_successfully'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:440:in `each'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:440:in `run_completed_successfully'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:299:in `run'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:295:in `block in fork_chef_client'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:283:in `fork'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:283:in `fork_chef_client'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:248:in `block in run_chef_client'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:236:in `run_chef_client'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:450:in `loop'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:450:in `interval_run_chef_client'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:434:in `run_application'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:59:in `run'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/bin/chef-client:26:in `<top (required)>'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/bin/chef-client:57:in `load'
[2017-05-13T01:54:24+00:00] ERROR: /opt/chef/bin/chef-client:57:in `<main>'
```

Is there a way to not have to provide an `access_key` and `secret_key`? Is there something else I should check

**Comment by zuazo** [comment]
Seems like maybe chef-handler-sns is not reading the IAM credentials from ohai correctly. Could you share you Ohai version and output of `ohai` command? (of course, blur your credentials before posting its output here).

**Comment by paulius005** [comment]
Ohai version: `5.1.0`. output obfuscated and attached. If you spot something I missed let me know :)
[output.txt](https://github.com/zuazo/chef_handler_sns-cookbook/files/998854/output.txt)

**Comment by zuazo** [comment]
Thanks for the information :wink:

Try enabling [`iam` hint](https://docs.chef.io/ohai.html#hints) in Ohai. See #3.

**Comment by paulius005** [comment]
Ah yep.

```
directory '/etc/chef/ohai/hints' do
  action :nothing
  recursive true
end.run_action(:create)

file '/etc/chef/ohai/hints/iam.json' do
  content '{}'
  action :nothing
end.run_action(:create)

ohai "reload" do
  action :nothing
end.run_action(:reload)
```

through that into the recipe and I was good. 

Thanks for your help!

Want me to add a section in the readme explaining that this must be enabled?

**Comment by zuazo** [comment]
Thanks for your feedback! :smile:

I'm thinking that maybe we should add that code directly to the cookbook. What do you think?

Another possibility is to use the `ohai_hint` resource from the [`ohai` cookbook](https://supermarket.chef.io/cookbooks/ohai):

```ruby
ohai_hint 'iam'
```
